import book from './assets/book.png'
import ratting from './assets/star.svg'
export const data=[
   {
    id:'1',
    title:"Javascript and Jquery",
    image:`${book}`,
    author:'Jon Duckett',
    price:62,
    ratting:`${ratting}`,
    PublicationYear:"2015",
    isFavorite:false,
   },
   {
    id:'2',
    title:"React and Jquery",
    image:`${book}`,
    author:'Jon',
    price:62,
    ratting:`${ratting}`,
    PublicationYear:"2019",
    isFavorite:false,
   },
   {
    id:'3',
    title:"Nodejs and Pythone",
    image:`${book}`,
    author:'Duckett',
    price:10,
    ratting:`${ratting}`,
    PublicationYear:"2022",
    isFavorite:true,
   },
   {
    id:'4',
    title:"HTML and CSS",
    image:`${book}`,
    author:'Jon Duckett',
    price:20,
    ratting:`${ratting}`,
    PublicationYear:"2023",
    isFavorite:false,
   },
   {
    id:'5',
    title:"CSS javascript",
    image:`${book}`,
    author:'Jon Duckett',
    price:100,
    ratting:`${ratting}`,
    PublicationYear:"2020",
    isFavorite:false,
   },
   {
    id:'6',
    title:"javascript",
    image:`${book}`,
    author:'Smrith',
    price:80,
    ratting:`${ratting}`,
    PublicationYear:"2014",
    isFavorite:false,
   },
   {
    id:'7',
    title:"PHP and Laravel",
    image:`${book}`,
    author:'Bratly',
    price:80,
    ratting:`${ratting}`,
    PublicationYear:"2018",
    isFavorite:false,
   },
   {
    id:'8',
    title:"Java",
    image:`${book}`,
    author:'John DUe',
    price:80,
    ratting:`${ratting}`,
    PublicationYear:"2020",
    isFavorite:false,
   }
]